server: 
  port: 9001
  
spring: 
  application: 
    name: spring-cloud-producer
    value: 
      test: GOOOOOOOOO

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:3000/eureka/
